### ISSUE TITLE
Influx error

### ISSUE THREAD

**Issue by InstigatorX** [cdzombak/ecobee_influx_connector#15] opened 2022-05-02 19:49 UTC
Getting this error when starting using the docker image.

Write error: Post "https://ha.xxxx.com:8086/api/v2/write?bucket=ecobee_upstairs&org=&precision=ns": x509: certificate relies on legacy Common Name field, use SANs instead

I'm on InfluxDB 1.8 and running it https

**Comment by cdzombak** [comment] 2022-05-02 20:20
This appears to be a problem with the TLS certificate your InfluxDB server is serving. I can't provide additional help without knowing how you generated that certificate, but if you search something like "golang x509: certificate relies on legacy Common Name field, use SANs instead" you'll find a number of discussions on how to generate a certificate correctly, like [this one](https://stackoverflow.com/a/68196866).

Closing, as this is due to [Golang behavior introduced in 1.15](https://golang.google.cn/doc/go1.15#commonname), and not a bug in this program.

**Closed by cdzombak** 2022-05-02 20:20 UTC
Labels: question

**Comment by cdzombak** [comment] 2022-05-02 20:21
The Golang changelog linked in my earlier comment also says the old (pre-1.15) behavior "can be temporarily re-enabled by adding the value x509ignoreCN=0 to the GODEBUG environment variable." I don't know if that environment variable still works, but you could try running ecobee_influx_connector with that variable set, and see if that helps as a workaround.

**Comment by InstigatorX** [comment] 2022-05-02 20:26
> The Golang changelog linked in my earlier comment also says the old (pre-1.15) behavior "can be temporarily re-enabled by adding the value `x509ignoreCN=0` to the `GODEBUG` environment variable." I don't know if that environment variable setting still works, but you could try running ecobee_influx_connector with that variable set, and see if that helps as a workaround.

Trying to figure that out now. Any thoughts on how I'd do that with the docker image? I tried adding .profile
